import { MigrationInterface, QueryRunner } from "typeorm";

export class Database1716259629171 implements MigrationInterface {
    name = 'Database1716259629171'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`freelancer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`apellido\` varchar(50) NOT NULL, \`cedula\` varchar(20) NOT NULL, \`fecha_nacimiento\` datetime NOT NULL, \`fondo\` varchar(255) NOT NULL, \`open_comissions\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, UNIQUE INDEX \`IDX_ceb7835d74d94467734c8ca1f5\` (\`usuarioId\`), UNIQUE INDEX \`REL_ceb7835d74d94467734c8ca1f5\` (\`usuarioId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`empresa\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ruc\` varchar(20) NOT NULL, \`razon_social\` varchar(100) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, UNIQUE INDEX \`IDX_dc656dc24f6986afbfe84ebf13\` (\`ruc\`), UNIQUE INDEX \`IDX_e0365e6ce010d4172df910ec49\` (\`usuarioId\`), UNIQUE INDEX \`REL_e0365e6ce010d4172df910ec49\` (\`usuarioId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`especialidad\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(50) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`like\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`publicacionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comentario\` (\`id\` int NOT NULL AUTO_INCREMENT, \`comentario\` varchar(150) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`publicacionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tipo_publicacion\` (\`id\` varchar(3) NOT NULL, \`tipo\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categoria\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(50) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision_imagenes_ejemplo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`imagen\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`comisionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tipo_transaccion\` (\`id\` varchar(3) NOT NULL, \`tipo\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ganancia\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cantidad\` decimal(10,2) NOT NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`tipoId\` varchar(3) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision_solicitud_estado\` (\`id\` varchar(3) NOT NULL, \`estado\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision_solicitud_entregables\` (\`id\` int NOT NULL AUTO_INCREMENT, \`archivo\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`solicitudId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision_solicitud\` (\`id\` int NOT NULL AUTO_INCREMENT, \`descripcion\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`comisionId\` int NULL, \`usuarioId\` int NULL, \`pagoId\` int NULL, \`gananciaId\` int NULL, \`estadoId\` varchar(3) NULL, UNIQUE INDEX \`REL_6e019cb0942113bd3f84c6d7fc\` (\`pagoId\`), UNIQUE INDEX \`REL_cc2fe0588f51a417261ec20239\` (\`gananciaId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(100) NOT NULL, \`descripcion\` text NOT NULL, \`precio\` decimal(10,2) NOT NULL, \`imagen\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subcategoria\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(50) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`categoriaId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`oferta_empleo_tipo\` (\`id\` varchar(3) NOT NULL, \`tipo\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`oferta_empleo_nivel\` (\`id\` varchar(3) NOT NULL, \`nivel\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`empleo_postulante\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`ofertaEmpleoId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`oferta_empleo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`descripcion\` text NOT NULL, \`vacantes\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`publicacionId\` int NULL, \`tipoId\` varchar(3) NULL, \`nivelId\` varchar(3) NULL, UNIQUE INDEX \`REL_b8836edcc7f22da38638add72c\` (\`publicacionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`articulo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`contenido\` longtext NOT NULL, \`portada\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`publicacionId\` int NULL, UNIQUE INDEX \`REL_74b35b4e514374ad717a165520\` (\`publicacionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`archivo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`archivo\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`publicacionId\` int NULL, UNIQUE INDEX \`REL_fbbf2c7597ba0bf282b5785789\` (\`publicacionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`publicacion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(100) NOT NULL, \`descripcion_corta\` text NOT NULL, \`publicado\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`tipoId\` varchar(3) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subespecialidad\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(50) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`especialidadId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`seguidores\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`seguidorId\` int NULL, \`seguidoId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tipo_seccion\` (\`id\` varchar(3) NOT NULL, \`nombre\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`texto_seccion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`texto\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`seccionId\` int NULL, UNIQUE INDEX \`IDX_0b036c0a8e2a770bcda8e41b02\` (\`seccionId\`), UNIQUE INDEX \`REL_0b036c0a8e2a770bcda8e41b02\` (\`seccionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`proyectos_seccion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`nombre\` varchar(100) NOT NULL, \`descripcion\` varchar(200) NOT NULL, \`imagen\` varchar(255) NOT NULL, \`enlace\` varchar(255) NOT NULL, \`fecha_inicio\` datetime NOT NULL, \`fecha_fin\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`seccionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`archivos_seccion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`archivo\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`seccionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`seccion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orden\` int NOT NULL, \`titulo\` varchar(50) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`tipoSeccionId\` varchar(3) NULL, \`usuarioId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`usuario\` (\`id\` int NOT NULL AUTO_INCREMENT, \`correo\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`nombre\` varchar(100) NOT NULL, \`foto\` varchar(255) NOT NULL, \`banner\` varchar(255) NOT NULL, \`fondo\` varchar(255) NOT NULL, \`about\` varchar(255) NOT NULL, \`telefono\` varchar(20) NOT NULL, \`tipo\` enum ('ADMINISTRADOR', 'FREELANCER', 'EMPRESA') NOT NULL DEFAULT 'FREELANCER', \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_349ecb64acc4355db443ca17cb\` (\`correo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pago\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cantidad\` decimal(10,2) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`usuarioId\` int NULL, \`tipoId\` varchar(3) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comision_subcategoria\` (\`comisionId\` int NOT NULL, \`subcategoriaId\` int NOT NULL, INDEX \`IDX_366b6f2e65a31ae7a9f9178805\` (\`comisionId\`), INDEX \`IDX_f1c346e406d4b3a3bfdb62d740\` (\`subcategoriaId\`), PRIMARY KEY (\`comisionId\`, \`subcategoriaId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`publicacion_subcategoria\` (\`publicacionId\` int NOT NULL, \`subcategoriaId\` int NOT NULL, INDEX \`IDX_17b92a980e9e1a2955e5a04043\` (\`publicacionId\`), INDEX \`IDX_27fd801d6dbc37ffa8285112fb\` (\`subcategoriaId\`), PRIMARY KEY (\`publicacionId\`, \`subcategoriaId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`publicacion_subespecialidad\` (\`publicacionId\` int NOT NULL, \`subespecialidadId\` int NOT NULL, INDEX \`IDX_3045d5c0adbd0be5cb8f221450\` (\`publicacionId\`), INDEX \`IDX_8f6e03892f67e3fbd4d715e107\` (\`subespecialidadId\`), PRIMARY KEY (\`publicacionId\`, \`subespecialidadId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`usuario_subespecialidad\` (\`usuarioId\` int NOT NULL, \`subespecialidadId\` int NOT NULL, INDEX \`IDX_870d469889fa9288afe6ccf79d\` (\`usuarioId\`), INDEX \`IDX_bb1f5f087134b76c054ae93928\` (\`subespecialidadId\`), PRIMARY KEY (\`usuarioId\`, \`subespecialidadId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`freelancer\` ADD CONSTRAINT \`FK_ceb7835d74d94467734c8ca1f5b\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`empresa\` ADD CONSTRAINT \`FK_e0365e6ce010d4172df910ec494\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`like\` ADD CONSTRAINT \`FK_87dcf990823d5449ebd1681cad5\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`like\` ADD CONSTRAINT \`FK_c3d99c9483a8fe26d45cb011f8f\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comentario\` ADD CONSTRAINT \`FK_8a91f1b066f78cd64570d95eb6e\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comentario\` ADD CONSTRAINT \`FK_71f95d912cda6a3108075fc41ef\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_imagenes_ejemplo\` ADD CONSTRAINT \`FK_1a8b2270f4b68fff5acaa8e1aa2\` FOREIGN KEY (\`comisionId\`) REFERENCES \`comision\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ganancia\` ADD CONSTRAINT \`FK_2615c6bd2dfa68d33e88328c93d\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ganancia\` ADD CONSTRAINT \`FK_d4e585a17a499894c685176be7d\` FOREIGN KEY (\`tipoId\`) REFERENCES \`tipo_transaccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud_entregables\` ADD CONSTRAINT \`FK_aa73e6f85d555f75661d63017d1\` FOREIGN KEY (\`solicitudId\`) REFERENCES \`comision_solicitud\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` ADD CONSTRAINT \`FK_f9afbf380a9b03b27cd4cd571e4\` FOREIGN KEY (\`comisionId\`) REFERENCES \`comision\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` ADD CONSTRAINT \`FK_c2976f4d7c76d5a9c4ec02bddab\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` ADD CONSTRAINT \`FK_6e019cb0942113bd3f84c6d7fc6\` FOREIGN KEY (\`pagoId\`) REFERENCES \`pago\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` ADD CONSTRAINT \`FK_cc2fe0588f51a417261ec20239e\` FOREIGN KEY (\`gananciaId\`) REFERENCES \`ganancia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` ADD CONSTRAINT \`FK_9a98a51c8a4a5cc53f7f473916b\` FOREIGN KEY (\`estadoId\`) REFERENCES \`comision_solicitud_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision\` ADD CONSTRAINT \`FK_1ca6e80ba79fe2388200cd2904e\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subcategoria\` ADD CONSTRAINT \`FK_e3cc887e6961ff4f9e3e34b29da\` FOREIGN KEY (\`categoriaId\`) REFERENCES \`categoria\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`empleo_postulante\` ADD CONSTRAINT \`FK_c863ce44b6682274062bbc6461e\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`empleo_postulante\` ADD CONSTRAINT \`FK_3a2ac5b2bf712a0553233ed8a82\` FOREIGN KEY (\`ofertaEmpleoId\`) REFERENCES \`oferta_empleo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` ADD CONSTRAINT \`FK_b8836edcc7f22da38638add72c2\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` ADD CONSTRAINT \`FK_1e453d8196a812e77853f094611\` FOREIGN KEY (\`tipoId\`) REFERENCES \`oferta_empleo_tipo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` ADD CONSTRAINT \`FK_729736584a1b68bf179b45e4f04\` FOREIGN KEY (\`nivelId\`) REFERENCES \`oferta_empleo_nivel\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`articulo\` ADD CONSTRAINT \`FK_74b35b4e514374ad717a1655203\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`archivo\` ADD CONSTRAINT \`FK_fbbf2c7597ba0bf282b57857892\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`publicacion\` ADD CONSTRAINT \`FK_1b02a56ed6cf029df51af7aee32\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`publicacion\` ADD CONSTRAINT \`FK_0789acafb0b87f0395bcdec8dd4\` FOREIGN KEY (\`tipoId\`) REFERENCES \`tipo_publicacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subespecialidad\` ADD CONSTRAINT \`FK_1d26431a6ff318f70f4af753155\` FOREIGN KEY (\`especialidadId\`) REFERENCES \`especialidad\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`seguidores\` ADD CONSTRAINT \`FK_24409f4ea7c4ceda065da935d14\` FOREIGN KEY (\`seguidorId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seguidores\` ADD CONSTRAINT \`FK_f6654d5441c1039c2e367880ea9\` FOREIGN KEY (\`seguidoId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`texto_seccion\` ADD CONSTRAINT \`FK_0b036c0a8e2a770bcda8e41b02d\` FOREIGN KEY (\`seccionId\`) REFERENCES \`seccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`proyectos_seccion\` ADD CONSTRAINT \`FK_2bddc1f56b65f843d04f395d0d2\` FOREIGN KEY (\`seccionId\`) REFERENCES \`seccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`archivos_seccion\` ADD CONSTRAINT \`FK_dd1aa13e97a9df3cae5f56095ca\` FOREIGN KEY (\`seccionId\`) REFERENCES \`seccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seccion\` ADD CONSTRAINT \`FK_245080e951a721da51a303136b4\` FOREIGN KEY (\`tipoSeccionId\`) REFERENCES \`tipo_seccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seccion\` ADD CONSTRAINT \`FK_be00e2f991289e7170b0482bec8\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pago\` ADD CONSTRAINT \`FK_931ebb93af7144f3a1ef90662ad\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pago\` ADD CONSTRAINT \`FK_0413d0869c6c0d1d43747890c0e\` FOREIGN KEY (\`tipoId\`) REFERENCES \`tipo_transaccion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comision_subcategoria\` ADD CONSTRAINT \`FK_366b6f2e65a31ae7a9f9178805c\` FOREIGN KEY (\`comisionId\`) REFERENCES \`comision\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`comision_subcategoria\` ADD CONSTRAINT \`FK_f1c346e406d4b3a3bfdb62d7401\` FOREIGN KEY (\`subcategoriaId\`) REFERENCES \`subcategoria\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`publicacion_subcategoria\` ADD CONSTRAINT \`FK_17b92a980e9e1a2955e5a040438\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`publicacion_subcategoria\` ADD CONSTRAINT \`FK_27fd801d6dbc37ffa8285112fb6\` FOREIGN KEY (\`subcategoriaId\`) REFERENCES \`subcategoria\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`publicacion_subespecialidad\` ADD CONSTRAINT \`FK_3045d5c0adbd0be5cb8f2214508\` FOREIGN KEY (\`publicacionId\`) REFERENCES \`publicacion\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`publicacion_subespecialidad\` ADD CONSTRAINT \`FK_8f6e03892f67e3fbd4d715e107f\` FOREIGN KEY (\`subespecialidadId\`) REFERENCES \`subespecialidad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuario_subespecialidad\` ADD CONSTRAINT \`FK_870d469889fa9288afe6ccf79d8\` FOREIGN KEY (\`usuarioId\`) REFERENCES \`usuario\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`usuario_subespecialidad\` ADD CONSTRAINT \`FK_bb1f5f087134b76c054ae939284\` FOREIGN KEY (\`subespecialidadId\`) REFERENCES \`subespecialidad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`usuario_subespecialidad\` DROP FOREIGN KEY \`FK_bb1f5f087134b76c054ae939284\``);
        await queryRunner.query(`ALTER TABLE \`usuario_subespecialidad\` DROP FOREIGN KEY \`FK_870d469889fa9288afe6ccf79d8\``);
        await queryRunner.query(`ALTER TABLE \`publicacion_subespecialidad\` DROP FOREIGN KEY \`FK_8f6e03892f67e3fbd4d715e107f\``);
        await queryRunner.query(`ALTER TABLE \`publicacion_subespecialidad\` DROP FOREIGN KEY \`FK_3045d5c0adbd0be5cb8f2214508\``);
        await queryRunner.query(`ALTER TABLE \`publicacion_subcategoria\` DROP FOREIGN KEY \`FK_27fd801d6dbc37ffa8285112fb6\``);
        await queryRunner.query(`ALTER TABLE \`publicacion_subcategoria\` DROP FOREIGN KEY \`FK_17b92a980e9e1a2955e5a040438\``);
        await queryRunner.query(`ALTER TABLE \`comision_subcategoria\` DROP FOREIGN KEY \`FK_f1c346e406d4b3a3bfdb62d7401\``);
        await queryRunner.query(`ALTER TABLE \`comision_subcategoria\` DROP FOREIGN KEY \`FK_366b6f2e65a31ae7a9f9178805c\``);
        await queryRunner.query(`ALTER TABLE \`pago\` DROP FOREIGN KEY \`FK_0413d0869c6c0d1d43747890c0e\``);
        await queryRunner.query(`ALTER TABLE \`pago\` DROP FOREIGN KEY \`FK_931ebb93af7144f3a1ef90662ad\``);
        await queryRunner.query(`ALTER TABLE \`seccion\` DROP FOREIGN KEY \`FK_be00e2f991289e7170b0482bec8\``);
        await queryRunner.query(`ALTER TABLE \`seccion\` DROP FOREIGN KEY \`FK_245080e951a721da51a303136b4\``);
        await queryRunner.query(`ALTER TABLE \`archivos_seccion\` DROP FOREIGN KEY \`FK_dd1aa13e97a9df3cae5f56095ca\``);
        await queryRunner.query(`ALTER TABLE \`proyectos_seccion\` DROP FOREIGN KEY \`FK_2bddc1f56b65f843d04f395d0d2\``);
        await queryRunner.query(`ALTER TABLE \`texto_seccion\` DROP FOREIGN KEY \`FK_0b036c0a8e2a770bcda8e41b02d\``);
        await queryRunner.query(`ALTER TABLE \`seguidores\` DROP FOREIGN KEY \`FK_f6654d5441c1039c2e367880ea9\``);
        await queryRunner.query(`ALTER TABLE \`seguidores\` DROP FOREIGN KEY \`FK_24409f4ea7c4ceda065da935d14\``);
        await queryRunner.query(`ALTER TABLE \`subespecialidad\` DROP FOREIGN KEY \`FK_1d26431a6ff318f70f4af753155\``);
        await queryRunner.query(`ALTER TABLE \`publicacion\` DROP FOREIGN KEY \`FK_0789acafb0b87f0395bcdec8dd4\``);
        await queryRunner.query(`ALTER TABLE \`publicacion\` DROP FOREIGN KEY \`FK_1b02a56ed6cf029df51af7aee32\``);
        await queryRunner.query(`ALTER TABLE \`archivo\` DROP FOREIGN KEY \`FK_fbbf2c7597ba0bf282b57857892\``);
        await queryRunner.query(`ALTER TABLE \`articulo\` DROP FOREIGN KEY \`FK_74b35b4e514374ad717a1655203\``);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` DROP FOREIGN KEY \`FK_729736584a1b68bf179b45e4f04\``);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` DROP FOREIGN KEY \`FK_1e453d8196a812e77853f094611\``);
        await queryRunner.query(`ALTER TABLE \`oferta_empleo\` DROP FOREIGN KEY \`FK_b8836edcc7f22da38638add72c2\``);
        await queryRunner.query(`ALTER TABLE \`empleo_postulante\` DROP FOREIGN KEY \`FK_3a2ac5b2bf712a0553233ed8a82\``);
        await queryRunner.query(`ALTER TABLE \`empleo_postulante\` DROP FOREIGN KEY \`FK_c863ce44b6682274062bbc6461e\``);
        await queryRunner.query(`ALTER TABLE \`subcategoria\` DROP FOREIGN KEY \`FK_e3cc887e6961ff4f9e3e34b29da\``);
        await queryRunner.query(`ALTER TABLE \`comision\` DROP FOREIGN KEY \`FK_1ca6e80ba79fe2388200cd2904e\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` DROP FOREIGN KEY \`FK_9a98a51c8a4a5cc53f7f473916b\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` DROP FOREIGN KEY \`FK_cc2fe0588f51a417261ec20239e\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` DROP FOREIGN KEY \`FK_6e019cb0942113bd3f84c6d7fc6\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` DROP FOREIGN KEY \`FK_c2976f4d7c76d5a9c4ec02bddab\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud\` DROP FOREIGN KEY \`FK_f9afbf380a9b03b27cd4cd571e4\``);
        await queryRunner.query(`ALTER TABLE \`comision_solicitud_entregables\` DROP FOREIGN KEY \`FK_aa73e6f85d555f75661d63017d1\``);
        await queryRunner.query(`ALTER TABLE \`ganancia\` DROP FOREIGN KEY \`FK_d4e585a17a499894c685176be7d\``);
        await queryRunner.query(`ALTER TABLE \`ganancia\` DROP FOREIGN KEY \`FK_2615c6bd2dfa68d33e88328c93d\``);
        await queryRunner.query(`ALTER TABLE \`comision_imagenes_ejemplo\` DROP FOREIGN KEY \`FK_1a8b2270f4b68fff5acaa8e1aa2\``);
        await queryRunner.query(`ALTER TABLE \`comentario\` DROP FOREIGN KEY \`FK_71f95d912cda6a3108075fc41ef\``);
        await queryRunner.query(`ALTER TABLE \`comentario\` DROP FOREIGN KEY \`FK_8a91f1b066f78cd64570d95eb6e\``);
        await queryRunner.query(`ALTER TABLE \`like\` DROP FOREIGN KEY \`FK_c3d99c9483a8fe26d45cb011f8f\``);
        await queryRunner.query(`ALTER TABLE \`like\` DROP FOREIGN KEY \`FK_87dcf990823d5449ebd1681cad5\``);
        await queryRunner.query(`ALTER TABLE \`empresa\` DROP FOREIGN KEY \`FK_e0365e6ce010d4172df910ec494\``);
        await queryRunner.query(`ALTER TABLE \`freelancer\` DROP FOREIGN KEY \`FK_ceb7835d74d94467734c8ca1f5b\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb1f5f087134b76c054ae93928\` ON \`usuario_subespecialidad\``);
        await queryRunner.query(`DROP INDEX \`IDX_870d469889fa9288afe6ccf79d\` ON \`usuario_subespecialidad\``);
        await queryRunner.query(`DROP TABLE \`usuario_subespecialidad\``);
        await queryRunner.query(`DROP INDEX \`IDX_8f6e03892f67e3fbd4d715e107\` ON \`publicacion_subespecialidad\``);
        await queryRunner.query(`DROP INDEX \`IDX_3045d5c0adbd0be5cb8f221450\` ON \`publicacion_subespecialidad\``);
        await queryRunner.query(`DROP TABLE \`publicacion_subespecialidad\``);
        await queryRunner.query(`DROP INDEX \`IDX_27fd801d6dbc37ffa8285112fb\` ON \`publicacion_subcategoria\``);
        await queryRunner.query(`DROP INDEX \`IDX_17b92a980e9e1a2955e5a04043\` ON \`publicacion_subcategoria\``);
        await queryRunner.query(`DROP TABLE \`publicacion_subcategoria\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1c346e406d4b3a3bfdb62d740\` ON \`comision_subcategoria\``);
        await queryRunner.query(`DROP INDEX \`IDX_366b6f2e65a31ae7a9f9178805\` ON \`comision_subcategoria\``);
        await queryRunner.query(`DROP TABLE \`comision_subcategoria\``);
        await queryRunner.query(`DROP TABLE \`pago\``);
        await queryRunner.query(`DROP INDEX \`IDX_349ecb64acc4355db443ca17cb\` ON \`usuario\``);
        await queryRunner.query(`DROP TABLE \`usuario\``);
        await queryRunner.query(`DROP TABLE \`seccion\``);
        await queryRunner.query(`DROP TABLE \`archivos_seccion\``);
        await queryRunner.query(`DROP TABLE \`proyectos_seccion\``);
        await queryRunner.query(`DROP INDEX \`REL_0b036c0a8e2a770bcda8e41b02\` ON \`texto_seccion\``);
        await queryRunner.query(`DROP INDEX \`IDX_0b036c0a8e2a770bcda8e41b02\` ON \`texto_seccion\``);
        await queryRunner.query(`DROP TABLE \`texto_seccion\``);
        await queryRunner.query(`DROP TABLE \`tipo_seccion\``);
        await queryRunner.query(`DROP TABLE \`seguidores\``);
        await queryRunner.query(`DROP TABLE \`subespecialidad\``);
        await queryRunner.query(`DROP TABLE \`publicacion\``);
        await queryRunner.query(`DROP INDEX \`REL_fbbf2c7597ba0bf282b5785789\` ON \`archivo\``);
        await queryRunner.query(`DROP TABLE \`archivo\``);
        await queryRunner.query(`DROP INDEX \`REL_74b35b4e514374ad717a165520\` ON \`articulo\``);
        await queryRunner.query(`DROP TABLE \`articulo\``);
        await queryRunner.query(`DROP INDEX \`REL_b8836edcc7f22da38638add72c\` ON \`oferta_empleo\``);
        await queryRunner.query(`DROP TABLE \`oferta_empleo\``);
        await queryRunner.query(`DROP TABLE \`empleo_postulante\``);
        await queryRunner.query(`DROP TABLE \`oferta_empleo_nivel\``);
        await queryRunner.query(`DROP TABLE \`oferta_empleo_tipo\``);
        await queryRunner.query(`DROP TABLE \`subcategoria\``);
        await queryRunner.query(`DROP TABLE \`comision\``);
        await queryRunner.query(`DROP INDEX \`REL_cc2fe0588f51a417261ec20239\` ON \`comision_solicitud\``);
        await queryRunner.query(`DROP INDEX \`REL_6e019cb0942113bd3f84c6d7fc\` ON \`comision_solicitud\``);
        await queryRunner.query(`DROP TABLE \`comision_solicitud\``);
        await queryRunner.query(`DROP TABLE \`comision_solicitud_entregables\``);
        await queryRunner.query(`DROP TABLE \`comision_solicitud_estado\``);
        await queryRunner.query(`DROP TABLE \`ganancia\``);
        await queryRunner.query(`DROP TABLE \`tipo_transaccion\``);
        await queryRunner.query(`DROP TABLE \`comision_imagenes_ejemplo\``);
        await queryRunner.query(`DROP TABLE \`categoria\``);
        await queryRunner.query(`DROP TABLE \`tipo_publicacion\``);
        await queryRunner.query(`DROP TABLE \`comentario\``);
        await queryRunner.query(`DROP TABLE \`like\``);
        await queryRunner.query(`DROP TABLE \`especialidad\``);
        await queryRunner.query(`DROP INDEX \`REL_e0365e6ce010d4172df910ec49\` ON \`empresa\``);
        await queryRunner.query(`DROP INDEX \`IDX_e0365e6ce010d4172df910ec49\` ON \`empresa\``);
        await queryRunner.query(`DROP INDEX \`IDX_dc656dc24f6986afbfe84ebf13\` ON \`empresa\``);
        await queryRunner.query(`DROP TABLE \`empresa\``);
        await queryRunner.query(`DROP INDEX \`REL_ceb7835d74d94467734c8ca1f5\` ON \`freelancer\``);
        await queryRunner.query(`DROP INDEX \`IDX_ceb7835d74d94467734c8ca1f5\` ON \`freelancer\``);
        await queryRunner.query(`DROP TABLE \`freelancer\``);
    }

}
